class FiatCurrency {
  final String code;
  final String name;
  final String symbol;
  final int decimalDigits;

  const FiatCurrency({
    required this.code,
    required this.name,
    required this.symbol,
    required this.decimalDigits,
  });
}

const List<FiatCurrency> fiatCurrencies = [
  FiatCurrency(
    code: 'ARS',
    name: 'Argentine Peso',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'BDT',
    name: 'Bangladeshi Taka',
    symbol: '৳',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'BIF',
    name: 'Burundian Franc',
    symbol: 'FBu',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'BOB',
    name: 'Bolivian Boliviano',
    symbol: '\$b',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'BRL',
    name: 'Brazilian Real',
    symbol: 'R\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'BTN',
    name: 'Bhutanese Ngultrum',
    symbol: 'Nu.',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'BWP',
    name: 'Botswanan Pula',
    symbol: 'P',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'CDF',
    name: 'Congolese Franc',
    symbol: 'FC',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'CHF',
    name: 'Swiss Franc',
    symbol: 'CHF',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'CLP',
    name: 'Chilean Peso',
    symbol: '\$',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'CNY',
    name: 'Chinese Yuan',
    symbol: '¥',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'COP',
    name: 'Colombian Peso',
    symbol: '\$',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'CRC',
    name: 'Costa Rican Colón',
    symbol: '₡',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'CUP',
    name: 'Cuban Peso',
    symbol: '\$MN',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'CZK',
    name: 'Czech Koruna',
    symbol: 'Kč',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'DJF',
    name: 'Djiboutian Franc',
    symbol: 'Fdj',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'DOP',
    name: 'Dominican Peso',
    symbol: 'RD\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'ERN',
    name: 'Eritrean Nakfa',
    symbol: 'Nfk',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'ETB',
    name: 'Ethiopian Birr',
    symbol: 'Br',
    decimalDigits: 2,
  ),
  FiatCurrency(code: 'EUR', name: 'Euro', symbol: '€', decimalDigits: 2),
  FiatCurrency(
    code: 'GBP',
    name: 'British Pound',
    symbol: '£',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'GHS',
    name: 'Ghanaian Cedi',
    symbol: '₵',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'GTQ',
    name: 'Guatemalan Quetzal',
    symbol: 'Q',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'HNL',
    name: 'Honduran Lempira',
    symbol: 'L',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'IDR',
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'KSh',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'KHR',
    name: 'Cambodian Riel',
    symbol: '៛',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'KRW',
    name: 'South Korean Won',
    symbol: '₩',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'LBP',
    name: 'Lebanese Pound',
    symbol: 'ل.ل',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'LKR',
    name: 'Sri Lankan Rupee',
    symbol: '₨',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'MMK',
    name: 'Myanmar Kyat',
    symbol: 'Ks',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'MWK',
    name: 'Malawian Kwacha',
    symbol: 'MK',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'MXN',
    name: 'Mexican Peso',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'MZN',
    name: 'Mozambican Metical',
    symbol: 'MT',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'NAD',
    name: 'Namibian Dollar',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'NGN',
    name: 'Nigerian Naira',
    symbol: '₦',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'NIO',
    name: 'Nicaraguan Córdoba',
    symbol: 'C\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'PAB',
    name: 'Panamanian Balboa',
    symbol: 'B/.',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'PEN',
    name: 'Peruvian Sol',
    symbol: 'S/.',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'PHP',
    name: 'Philippine Peso',
    symbol: '₱',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'PKR',
    name: 'Pakistani Rupee',
    symbol: '₨',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'PLN',
    name: 'Polish Zloty',
    symbol: 'zł',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'PYG',
    name: 'Paraguayan Guarani',
    symbol: '₲',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'RWF',
    name: 'Rwandan Franc',
    symbol: 'FRw',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'SDG',
    name: 'Sudanese Pound',
    symbol: 'ج.س',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'SOS',
    name: 'Somali Shilling',
    symbol: 'S',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'SRD',
    name: 'Surinamese Dollar',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(code: 'THB', name: 'Thai Baht', symbol: '฿', decimalDigits: 2),
  FiatCurrency(
    code: 'TZS',
    name: 'Tanzanian Shilling',
    symbol: 'TSh',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'UAH',
    name: 'Ukrainian Hryvnia',
    symbol: '₴',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'UGX',
    name: 'Ugandan Shilling',
    symbol: 'USh',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'USD',
    name: 'United States Dollar',
    symbol: '\$',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'UYU',
    name: 'Uruguayan Peso',
    symbol: '\$U',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'VES',
    name: 'Venezuelan Bolívar',
    symbol: 'Bs',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'VND',
    name: 'Vietnamese Dong',
    symbol: '₫',
    decimalDigits: 0,
  ),
  FiatCurrency(
    code: 'XAF',
    name: 'Central African CFA Franc',
    symbol: 'FCFA',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'XOF',
    name: 'West African CFA Franc',
    symbol: 'FCFA',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'ZAR',
    name: 'South African Rand',
    symbol: 'R',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'ZMW',
    name: 'Zambian Kwacha',
    symbol: 'ZK',
    decimalDigits: 2,
  ),
  FiatCurrency(
    code: 'ZWL',
    name: 'Zimbabwean Dollar',
    symbol: '\$ZWL',
    decimalDigits: 2,
  ),
];
